version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_ACCOUNT_ID=${TMDB_ACCOUNT_ID}
      - TMDB_ACCESS_TOKEN=${TMDB_ACCESS_TOKEN}
      - CACHE_TTL=${CACHE_TTL}
    command: ["npm", "run", "start:prod"]
